language: python

python:
    - "2.6"
    - "2.7"

env: 
    - DEPS="numpy scipy nose"

# command to install dependencies (copied from jakevdp/supersmoother)
# using miniconda
before_install:
    - sudo apt-get install gfortran
    - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/anaconda/bin:$PATH
    - conda update --yes conda

install:
    - conda create -n testenv --yes python=$TRAVIS_PYTHON_VERSION
    - source activate testenv
    - conda install --yes $DEPS
    - python setup.py install

# command to run tests
script: 
    - nosetests